# Generated by Django 3.0.3 on 2020-06-21 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Covid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.CharField(blank=True, max_length=100)),
                ('Country', models.CharField(blank=True, max_length=100)),
                ('Confirmed', models.CharField(blank=True, max_length=1000000)),
                ('Recovered', models.CharField(blank=True, max_length=1000000)),
                ('Deaths', models.CharField(blank=True, max_length=1000000)),
            ],
        ),
    ]
